//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: google/pubsub/v1/schema.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Service for doing schema-related operations.
///
/// Usage: instantiate `Google_Pubsub_V1_SchemaServiceClient`, then call methods of this protocol to make API calls.
internal protocol Google_Pubsub_V1_SchemaServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Google_Pubsub_V1_SchemaServiceClientInterceptorFactoryProtocol? { get }

  func createSchema(
    _ request: Google_Pubsub_V1_CreateSchemaRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Pubsub_V1_CreateSchemaRequest, Google_Pubsub_V1_Schema>

  func getSchema(
    _ request: Google_Pubsub_V1_GetSchemaRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Pubsub_V1_GetSchemaRequest, Google_Pubsub_V1_Schema>

  func listSchemas(
    _ request: Google_Pubsub_V1_ListSchemasRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Pubsub_V1_ListSchemasRequest, Google_Pubsub_V1_ListSchemasResponse>

  func listSchemaRevisions(
    _ request: Google_Pubsub_V1_ListSchemaRevisionsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Pubsub_V1_ListSchemaRevisionsRequest, Google_Pubsub_V1_ListSchemaRevisionsResponse>

  func commitSchema(
    _ request: Google_Pubsub_V1_CommitSchemaRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Pubsub_V1_CommitSchemaRequest, Google_Pubsub_V1_Schema>

  func rollbackSchema(
    _ request: Google_Pubsub_V1_RollbackSchemaRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Pubsub_V1_RollbackSchemaRequest, Google_Pubsub_V1_Schema>

  func deleteSchemaRevision(
    _ request: Google_Pubsub_V1_DeleteSchemaRevisionRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Pubsub_V1_DeleteSchemaRevisionRequest, Google_Pubsub_V1_Schema>

  func deleteSchema(
    _ request: Google_Pubsub_V1_DeleteSchemaRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Pubsub_V1_DeleteSchemaRequest, SwiftProtobuf.Google_Protobuf_Empty>

  func validateSchema(
    _ request: Google_Pubsub_V1_ValidateSchemaRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Pubsub_V1_ValidateSchemaRequest, Google_Pubsub_V1_ValidateSchemaResponse>

  func validateMessage(
    _ request: Google_Pubsub_V1_ValidateMessageRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Pubsub_V1_ValidateMessageRequest, Google_Pubsub_V1_ValidateMessageResponse>
}

extension Google_Pubsub_V1_SchemaServiceClientProtocol {
  internal var serviceName: String {
    return "google.pubsub.v1.SchemaService"
  }

  /// Creates a schema.
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateSchema.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func createSchema(
    _ request: Google_Pubsub_V1_CreateSchemaRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Pubsub_V1_CreateSchemaRequest, Google_Pubsub_V1_Schema> {
    return self.makeUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.createSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateSchemaInterceptors() ?? []
    )
  }

  /// Gets a schema.
  ///
  /// - Parameters:
  ///   - request: Request to send to GetSchema.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getSchema(
    _ request: Google_Pubsub_V1_GetSchemaRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Pubsub_V1_GetSchemaRequest, Google_Pubsub_V1_Schema> {
    return self.makeUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.getSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetSchemaInterceptors() ?? []
    )
  }

  /// Lists schemas in a project.
  ///
  /// - Parameters:
  ///   - request: Request to send to ListSchemas.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func listSchemas(
    _ request: Google_Pubsub_V1_ListSchemasRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Pubsub_V1_ListSchemasRequest, Google_Pubsub_V1_ListSchemasResponse> {
    return self.makeUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.listSchemas.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListSchemasInterceptors() ?? []
    )
  }

  /// Lists all schema revisions for the named schema.
  ///
  /// - Parameters:
  ///   - request: Request to send to ListSchemaRevisions.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func listSchemaRevisions(
    _ request: Google_Pubsub_V1_ListSchemaRevisionsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Pubsub_V1_ListSchemaRevisionsRequest, Google_Pubsub_V1_ListSchemaRevisionsResponse> {
    return self.makeUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.listSchemaRevisions.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListSchemaRevisionsInterceptors() ?? []
    )
  }

  /// Commits a new schema revision to an existing schema.
  ///
  /// - Parameters:
  ///   - request: Request to send to CommitSchema.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func commitSchema(
    _ request: Google_Pubsub_V1_CommitSchemaRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Pubsub_V1_CommitSchemaRequest, Google_Pubsub_V1_Schema> {
    return self.makeUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.commitSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCommitSchemaInterceptors() ?? []
    )
  }

  /// Creates a new schema revision that is a copy of the provided revision_id.
  ///
  /// - Parameters:
  ///   - request: Request to send to RollbackSchema.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func rollbackSchema(
    _ request: Google_Pubsub_V1_RollbackSchemaRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Pubsub_V1_RollbackSchemaRequest, Google_Pubsub_V1_Schema> {
    return self.makeUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.rollbackSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRollbackSchemaInterceptors() ?? []
    )
  }

  /// Deletes a specific schema revision.
  ///
  /// - Parameters:
  ///   - request: Request to send to DeleteSchemaRevision.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func deleteSchemaRevision(
    _ request: Google_Pubsub_V1_DeleteSchemaRevisionRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Pubsub_V1_DeleteSchemaRevisionRequest, Google_Pubsub_V1_Schema> {
    return self.makeUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.deleteSchemaRevision.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteSchemaRevisionInterceptors() ?? []
    )
  }

  /// Deletes a schema.
  ///
  /// - Parameters:
  ///   - request: Request to send to DeleteSchema.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func deleteSchema(
    _ request: Google_Pubsub_V1_DeleteSchemaRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Pubsub_V1_DeleteSchemaRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.deleteSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteSchemaInterceptors() ?? []
    )
  }

  /// Validates a schema.
  ///
  /// - Parameters:
  ///   - request: Request to send to ValidateSchema.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func validateSchema(
    _ request: Google_Pubsub_V1_ValidateSchemaRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Pubsub_V1_ValidateSchemaRequest, Google_Pubsub_V1_ValidateSchemaResponse> {
    return self.makeUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.validateSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeValidateSchemaInterceptors() ?? []
    )
  }

  /// Validates a message against a schema.
  ///
  /// - Parameters:
  ///   - request: Request to send to ValidateMessage.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func validateMessage(
    _ request: Google_Pubsub_V1_ValidateMessageRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Pubsub_V1_ValidateMessageRequest, Google_Pubsub_V1_ValidateMessageResponse> {
    return self.makeUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.validateMessage.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeValidateMessageInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Google_Pubsub_V1_SchemaServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Google_Pubsub_V1_SchemaServiceNIOClient")
internal final class Google_Pubsub_V1_SchemaServiceClient: Google_Pubsub_V1_SchemaServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Google_Pubsub_V1_SchemaServiceClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Google_Pubsub_V1_SchemaServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the google.pubsub.v1.SchemaService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Google_Pubsub_V1_SchemaServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Google_Pubsub_V1_SchemaServiceNIOClient: Google_Pubsub_V1_SchemaServiceClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Google_Pubsub_V1_SchemaServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the google.pubsub.v1.SchemaService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Google_Pubsub_V1_SchemaServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// Service for doing schema-related operations.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Google_Pubsub_V1_SchemaServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Google_Pubsub_V1_SchemaServiceClientInterceptorFactoryProtocol? { get }

  func makeCreateSchemaCall(
    _ request: Google_Pubsub_V1_CreateSchemaRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_CreateSchemaRequest, Google_Pubsub_V1_Schema>

  func makeGetSchemaCall(
    _ request: Google_Pubsub_V1_GetSchemaRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_GetSchemaRequest, Google_Pubsub_V1_Schema>

  func makeListSchemasCall(
    _ request: Google_Pubsub_V1_ListSchemasRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_ListSchemasRequest, Google_Pubsub_V1_ListSchemasResponse>

  func makeListSchemaRevisionsCall(
    _ request: Google_Pubsub_V1_ListSchemaRevisionsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_ListSchemaRevisionsRequest, Google_Pubsub_V1_ListSchemaRevisionsResponse>

  func makeCommitSchemaCall(
    _ request: Google_Pubsub_V1_CommitSchemaRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_CommitSchemaRequest, Google_Pubsub_V1_Schema>

  func makeRollbackSchemaCall(
    _ request: Google_Pubsub_V1_RollbackSchemaRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_RollbackSchemaRequest, Google_Pubsub_V1_Schema>

  func makeDeleteSchemaRevisionCall(
    _ request: Google_Pubsub_V1_DeleteSchemaRevisionRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_DeleteSchemaRevisionRequest, Google_Pubsub_V1_Schema>

  func makeDeleteSchemaCall(
    _ request: Google_Pubsub_V1_DeleteSchemaRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_DeleteSchemaRequest, SwiftProtobuf.Google_Protobuf_Empty>

  func makeValidateSchemaCall(
    _ request: Google_Pubsub_V1_ValidateSchemaRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_ValidateSchemaRequest, Google_Pubsub_V1_ValidateSchemaResponse>

  func makeValidateMessageCall(
    _ request: Google_Pubsub_V1_ValidateMessageRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_ValidateMessageRequest, Google_Pubsub_V1_ValidateMessageResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Google_Pubsub_V1_SchemaServiceAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Google_Pubsub_V1_SchemaServiceClientMetadata.serviceDescriptor
  }

  internal var interceptors: Google_Pubsub_V1_SchemaServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeCreateSchemaCall(
    _ request: Google_Pubsub_V1_CreateSchemaRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_CreateSchemaRequest, Google_Pubsub_V1_Schema> {
    return self.makeAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.createSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateSchemaInterceptors() ?? []
    )
  }

  internal func makeGetSchemaCall(
    _ request: Google_Pubsub_V1_GetSchemaRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_GetSchemaRequest, Google_Pubsub_V1_Schema> {
    return self.makeAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.getSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetSchemaInterceptors() ?? []
    )
  }

  internal func makeListSchemasCall(
    _ request: Google_Pubsub_V1_ListSchemasRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_ListSchemasRequest, Google_Pubsub_V1_ListSchemasResponse> {
    return self.makeAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.listSchemas.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListSchemasInterceptors() ?? []
    )
  }

  internal func makeListSchemaRevisionsCall(
    _ request: Google_Pubsub_V1_ListSchemaRevisionsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_ListSchemaRevisionsRequest, Google_Pubsub_V1_ListSchemaRevisionsResponse> {
    return self.makeAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.listSchemaRevisions.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListSchemaRevisionsInterceptors() ?? []
    )
  }

  internal func makeCommitSchemaCall(
    _ request: Google_Pubsub_V1_CommitSchemaRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_CommitSchemaRequest, Google_Pubsub_V1_Schema> {
    return self.makeAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.commitSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCommitSchemaInterceptors() ?? []
    )
  }

  internal func makeRollbackSchemaCall(
    _ request: Google_Pubsub_V1_RollbackSchemaRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_RollbackSchemaRequest, Google_Pubsub_V1_Schema> {
    return self.makeAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.rollbackSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRollbackSchemaInterceptors() ?? []
    )
  }

  internal func makeDeleteSchemaRevisionCall(
    _ request: Google_Pubsub_V1_DeleteSchemaRevisionRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_DeleteSchemaRevisionRequest, Google_Pubsub_V1_Schema> {
    return self.makeAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.deleteSchemaRevision.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteSchemaRevisionInterceptors() ?? []
    )
  }

  internal func makeDeleteSchemaCall(
    _ request: Google_Pubsub_V1_DeleteSchemaRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_DeleteSchemaRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.deleteSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteSchemaInterceptors() ?? []
    )
  }

  internal func makeValidateSchemaCall(
    _ request: Google_Pubsub_V1_ValidateSchemaRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_ValidateSchemaRequest, Google_Pubsub_V1_ValidateSchemaResponse> {
    return self.makeAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.validateSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeValidateSchemaInterceptors() ?? []
    )
  }

  internal func makeValidateMessageCall(
    _ request: Google_Pubsub_V1_ValidateMessageRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Google_Pubsub_V1_ValidateMessageRequest, Google_Pubsub_V1_ValidateMessageResponse> {
    return self.makeAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.validateMessage.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeValidateMessageInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Google_Pubsub_V1_SchemaServiceAsyncClientProtocol {
  internal func createSchema(
    _ request: Google_Pubsub_V1_CreateSchemaRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Google_Pubsub_V1_Schema {
    return try await self.performAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.createSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateSchemaInterceptors() ?? []
    )
  }

  internal func getSchema(
    _ request: Google_Pubsub_V1_GetSchemaRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Google_Pubsub_V1_Schema {
    return try await self.performAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.getSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetSchemaInterceptors() ?? []
    )
  }

  internal func listSchemas(
    _ request: Google_Pubsub_V1_ListSchemasRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Google_Pubsub_V1_ListSchemasResponse {
    return try await self.performAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.listSchemas.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListSchemasInterceptors() ?? []
    )
  }

  internal func listSchemaRevisions(
    _ request: Google_Pubsub_V1_ListSchemaRevisionsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Google_Pubsub_V1_ListSchemaRevisionsResponse {
    return try await self.performAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.listSchemaRevisions.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListSchemaRevisionsInterceptors() ?? []
    )
  }

  internal func commitSchema(
    _ request: Google_Pubsub_V1_CommitSchemaRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Google_Pubsub_V1_Schema {
    return try await self.performAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.commitSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCommitSchemaInterceptors() ?? []
    )
  }

  internal func rollbackSchema(
    _ request: Google_Pubsub_V1_RollbackSchemaRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Google_Pubsub_V1_Schema {
    return try await self.performAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.rollbackSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRollbackSchemaInterceptors() ?? []
    )
  }

  internal func deleteSchemaRevision(
    _ request: Google_Pubsub_V1_DeleteSchemaRevisionRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Google_Pubsub_V1_Schema {
    return try await self.performAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.deleteSchemaRevision.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteSchemaRevisionInterceptors() ?? []
    )
  }

  internal func deleteSchema(
    _ request: Google_Pubsub_V1_DeleteSchemaRequest,
    callOptions: CallOptions? = nil
  ) async throws -> SwiftProtobuf.Google_Protobuf_Empty {
    return try await self.performAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.deleteSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteSchemaInterceptors() ?? []
    )
  }

  internal func validateSchema(
    _ request: Google_Pubsub_V1_ValidateSchemaRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Google_Pubsub_V1_ValidateSchemaResponse {
    return try await self.performAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.validateSchema.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeValidateSchemaInterceptors() ?? []
    )
  }

  internal func validateMessage(
    _ request: Google_Pubsub_V1_ValidateMessageRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Google_Pubsub_V1_ValidateMessageResponse {
    return try await self.performAsyncUnaryCall(
      path: Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.validateMessage.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeValidateMessageInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Google_Pubsub_V1_SchemaServiceAsyncClient: Google_Pubsub_V1_SchemaServiceAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Google_Pubsub_V1_SchemaServiceClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Google_Pubsub_V1_SchemaServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Google_Pubsub_V1_SchemaServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'createSchema'.
  func makeCreateSchemaInterceptors() -> [ClientInterceptor<Google_Pubsub_V1_CreateSchemaRequest, Google_Pubsub_V1_Schema>]

  /// - Returns: Interceptors to use when invoking 'getSchema'.
  func makeGetSchemaInterceptors() -> [ClientInterceptor<Google_Pubsub_V1_GetSchemaRequest, Google_Pubsub_V1_Schema>]

  /// - Returns: Interceptors to use when invoking 'listSchemas'.
  func makeListSchemasInterceptors() -> [ClientInterceptor<Google_Pubsub_V1_ListSchemasRequest, Google_Pubsub_V1_ListSchemasResponse>]

  /// - Returns: Interceptors to use when invoking 'listSchemaRevisions'.
  func makeListSchemaRevisionsInterceptors() -> [ClientInterceptor<Google_Pubsub_V1_ListSchemaRevisionsRequest, Google_Pubsub_V1_ListSchemaRevisionsResponse>]

  /// - Returns: Interceptors to use when invoking 'commitSchema'.
  func makeCommitSchemaInterceptors() -> [ClientInterceptor<Google_Pubsub_V1_CommitSchemaRequest, Google_Pubsub_V1_Schema>]

  /// - Returns: Interceptors to use when invoking 'rollbackSchema'.
  func makeRollbackSchemaInterceptors() -> [ClientInterceptor<Google_Pubsub_V1_RollbackSchemaRequest, Google_Pubsub_V1_Schema>]

  /// - Returns: Interceptors to use when invoking 'deleteSchemaRevision'.
  func makeDeleteSchemaRevisionInterceptors() -> [ClientInterceptor<Google_Pubsub_V1_DeleteSchemaRevisionRequest, Google_Pubsub_V1_Schema>]

  /// - Returns: Interceptors to use when invoking 'deleteSchema'.
  func makeDeleteSchemaInterceptors() -> [ClientInterceptor<Google_Pubsub_V1_DeleteSchemaRequest, SwiftProtobuf.Google_Protobuf_Empty>]

  /// - Returns: Interceptors to use when invoking 'validateSchema'.
  func makeValidateSchemaInterceptors() -> [ClientInterceptor<Google_Pubsub_V1_ValidateSchemaRequest, Google_Pubsub_V1_ValidateSchemaResponse>]

  /// - Returns: Interceptors to use when invoking 'validateMessage'.
  func makeValidateMessageInterceptors() -> [ClientInterceptor<Google_Pubsub_V1_ValidateMessageRequest, Google_Pubsub_V1_ValidateMessageResponse>]
}

internal enum Google_Pubsub_V1_SchemaServiceClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "SchemaService",
    fullName: "google.pubsub.v1.SchemaService",
    methods: [
      Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.createSchema,
      Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.getSchema,
      Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.listSchemas,
      Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.listSchemaRevisions,
      Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.commitSchema,
      Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.rollbackSchema,
      Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.deleteSchemaRevision,
      Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.deleteSchema,
      Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.validateSchema,
      Google_Pubsub_V1_SchemaServiceClientMetadata.Methods.validateMessage,
    ]
  )

  internal enum Methods {
    internal static let createSchema = GRPCMethodDescriptor(
      name: "CreateSchema",
      path: "/google.pubsub.v1.SchemaService/CreateSchema",
      type: GRPCCallType.unary
    )

    internal static let getSchema = GRPCMethodDescriptor(
      name: "GetSchema",
      path: "/google.pubsub.v1.SchemaService/GetSchema",
      type: GRPCCallType.unary
    )

    internal static let listSchemas = GRPCMethodDescriptor(
      name: "ListSchemas",
      path: "/google.pubsub.v1.SchemaService/ListSchemas",
      type: GRPCCallType.unary
    )

    internal static let listSchemaRevisions = GRPCMethodDescriptor(
      name: "ListSchemaRevisions",
      path: "/google.pubsub.v1.SchemaService/ListSchemaRevisions",
      type: GRPCCallType.unary
    )

    internal static let commitSchema = GRPCMethodDescriptor(
      name: "CommitSchema",
      path: "/google.pubsub.v1.SchemaService/CommitSchema",
      type: GRPCCallType.unary
    )

    internal static let rollbackSchema = GRPCMethodDescriptor(
      name: "RollbackSchema",
      path: "/google.pubsub.v1.SchemaService/RollbackSchema",
      type: GRPCCallType.unary
    )

    internal static let deleteSchemaRevision = GRPCMethodDescriptor(
      name: "DeleteSchemaRevision",
      path: "/google.pubsub.v1.SchemaService/DeleteSchemaRevision",
      type: GRPCCallType.unary
    )

    internal static let deleteSchema = GRPCMethodDescriptor(
      name: "DeleteSchema",
      path: "/google.pubsub.v1.SchemaService/DeleteSchema",
      type: GRPCCallType.unary
    )

    internal static let validateSchema = GRPCMethodDescriptor(
      name: "ValidateSchema",
      path: "/google.pubsub.v1.SchemaService/ValidateSchema",
      type: GRPCCallType.unary
    )

    internal static let validateMessage = GRPCMethodDescriptor(
      name: "ValidateMessage",
      path: "/google.pubsub.v1.SchemaService/ValidateMessage",
      type: GRPCCallType.unary
    )
  }
}

/// Service for doing schema-related operations.
///
/// To build a server, implement a class that conforms to this protocol.
internal protocol Google_Pubsub_V1_SchemaServiceProvider: CallHandlerProvider {
  var interceptors: Google_Pubsub_V1_SchemaServiceServerInterceptorFactoryProtocol? { get }

  /// Creates a schema.
  func createSchema(request: Google_Pubsub_V1_CreateSchemaRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Pubsub_V1_Schema>

  /// Gets a schema.
  func getSchema(request: Google_Pubsub_V1_GetSchemaRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Pubsub_V1_Schema>

  /// Lists schemas in a project.
  func listSchemas(request: Google_Pubsub_V1_ListSchemasRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Pubsub_V1_ListSchemasResponse>

  /// Lists all schema revisions for the named schema.
  func listSchemaRevisions(request: Google_Pubsub_V1_ListSchemaRevisionsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Pubsub_V1_ListSchemaRevisionsResponse>

  /// Commits a new schema revision to an existing schema.
  func commitSchema(request: Google_Pubsub_V1_CommitSchemaRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Pubsub_V1_Schema>

  /// Creates a new schema revision that is a copy of the provided revision_id.
  func rollbackSchema(request: Google_Pubsub_V1_RollbackSchemaRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Pubsub_V1_Schema>

  /// Deletes a specific schema revision.
  func deleteSchemaRevision(request: Google_Pubsub_V1_DeleteSchemaRevisionRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Pubsub_V1_Schema>

  /// Deletes a schema.
  func deleteSchema(request: Google_Pubsub_V1_DeleteSchemaRequest, context: StatusOnlyCallContext) -> EventLoopFuture<SwiftProtobuf.Google_Protobuf_Empty>

  /// Validates a schema.
  func validateSchema(request: Google_Pubsub_V1_ValidateSchemaRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Pubsub_V1_ValidateSchemaResponse>

  /// Validates a message against a schema.
  func validateMessage(request: Google_Pubsub_V1_ValidateMessageRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Pubsub_V1_ValidateMessageResponse>
}

extension Google_Pubsub_V1_SchemaServiceProvider {
  internal var serviceName: Substring {
    return Google_Pubsub_V1_SchemaServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "CreateSchema":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Pubsub_V1_CreateSchemaRequest>(),
        responseSerializer: ProtobufSerializer<Google_Pubsub_V1_Schema>(),
        interceptors: self.interceptors?.makeCreateSchemaInterceptors() ?? [],
        userFunction: self.createSchema(request:context:)
      )

    case "GetSchema":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Pubsub_V1_GetSchemaRequest>(),
        responseSerializer: ProtobufSerializer<Google_Pubsub_V1_Schema>(),
        interceptors: self.interceptors?.makeGetSchemaInterceptors() ?? [],
        userFunction: self.getSchema(request:context:)
      )

    case "ListSchemas":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Pubsub_V1_ListSchemasRequest>(),
        responseSerializer: ProtobufSerializer<Google_Pubsub_V1_ListSchemasResponse>(),
        interceptors: self.interceptors?.makeListSchemasInterceptors() ?? [],
        userFunction: self.listSchemas(request:context:)
      )

    case "ListSchemaRevisions":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Pubsub_V1_ListSchemaRevisionsRequest>(),
        responseSerializer: ProtobufSerializer<Google_Pubsub_V1_ListSchemaRevisionsResponse>(),
        interceptors: self.interceptors?.makeListSchemaRevisionsInterceptors() ?? [],
        userFunction: self.listSchemaRevisions(request:context:)
      )

    case "CommitSchema":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Pubsub_V1_CommitSchemaRequest>(),
        responseSerializer: ProtobufSerializer<Google_Pubsub_V1_Schema>(),
        interceptors: self.interceptors?.makeCommitSchemaInterceptors() ?? [],
        userFunction: self.commitSchema(request:context:)
      )

    case "RollbackSchema":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Pubsub_V1_RollbackSchemaRequest>(),
        responseSerializer: ProtobufSerializer<Google_Pubsub_V1_Schema>(),
        interceptors: self.interceptors?.makeRollbackSchemaInterceptors() ?? [],
        userFunction: self.rollbackSchema(request:context:)
      )

    case "DeleteSchemaRevision":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Pubsub_V1_DeleteSchemaRevisionRequest>(),
        responseSerializer: ProtobufSerializer<Google_Pubsub_V1_Schema>(),
        interceptors: self.interceptors?.makeDeleteSchemaRevisionInterceptors() ?? [],
        userFunction: self.deleteSchemaRevision(request:context:)
      )

    case "DeleteSchema":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Pubsub_V1_DeleteSchemaRequest>(),
        responseSerializer: ProtobufSerializer<SwiftProtobuf.Google_Protobuf_Empty>(),
        interceptors: self.interceptors?.makeDeleteSchemaInterceptors() ?? [],
        userFunction: self.deleteSchema(request:context:)
      )

    case "ValidateSchema":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Pubsub_V1_ValidateSchemaRequest>(),
        responseSerializer: ProtobufSerializer<Google_Pubsub_V1_ValidateSchemaResponse>(),
        interceptors: self.interceptors?.makeValidateSchemaInterceptors() ?? [],
        userFunction: self.validateSchema(request:context:)
      )

    case "ValidateMessage":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Pubsub_V1_ValidateMessageRequest>(),
        responseSerializer: ProtobufSerializer<Google_Pubsub_V1_ValidateMessageResponse>(),
        interceptors: self.interceptors?.makeValidateMessageInterceptors() ?? [],
        userFunction: self.validateMessage(request:context:)
      )

    default:
      return nil
    }
  }
}

/// Service for doing schema-related operations.
///
/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Google_Pubsub_V1_SchemaServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Google_Pubsub_V1_SchemaServiceServerInterceptorFactoryProtocol? { get }

  /// Creates a schema.
  func createSchema(
    request: Google_Pubsub_V1_CreateSchemaRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Google_Pubsub_V1_Schema

  /// Gets a schema.
  func getSchema(
    request: Google_Pubsub_V1_GetSchemaRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Google_Pubsub_V1_Schema

  /// Lists schemas in a project.
  func listSchemas(
    request: Google_Pubsub_V1_ListSchemasRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Google_Pubsub_V1_ListSchemasResponse

  /// Lists all schema revisions for the named schema.
  func listSchemaRevisions(
    request: Google_Pubsub_V1_ListSchemaRevisionsRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Google_Pubsub_V1_ListSchemaRevisionsResponse

  /// Commits a new schema revision to an existing schema.
  func commitSchema(
    request: Google_Pubsub_V1_CommitSchemaRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Google_Pubsub_V1_Schema

  /// Creates a new schema revision that is a copy of the provided revision_id.
  func rollbackSchema(
    request: Google_Pubsub_V1_RollbackSchemaRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Google_Pubsub_V1_Schema

  /// Deletes a specific schema revision.
  func deleteSchemaRevision(
    request: Google_Pubsub_V1_DeleteSchemaRevisionRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Google_Pubsub_V1_Schema

  /// Deletes a schema.
  func deleteSchema(
    request: Google_Pubsub_V1_DeleteSchemaRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> SwiftProtobuf.Google_Protobuf_Empty

  /// Validates a schema.
  func validateSchema(
    request: Google_Pubsub_V1_ValidateSchemaRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Google_Pubsub_V1_ValidateSchemaResponse

  /// Validates a message against a schema.
  func validateMessage(
    request: Google_Pubsub_V1_ValidateMessageRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Google_Pubsub_V1_ValidateMessageResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Google_Pubsub_V1_SchemaServiceAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Google_Pubsub_V1_SchemaServiceServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Google_Pubsub_V1_SchemaServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Google_Pubsub_V1_SchemaServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "CreateSchema":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Pubsub_V1_CreateSchemaRequest>(),
        responseSerializer: ProtobufSerializer<Google_Pubsub_V1_Schema>(),
        interceptors: self.interceptors?.makeCreateSchemaInterceptors() ?? [],
        wrapping: { try await self.createSchema(request: $0, context: $1) }
      )

    case "GetSchema":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Pubsub_V1_GetSchemaRequest>(),
        responseSerializer: ProtobufSerializer<Google_Pubsub_V1_Schema>(),
        interceptors: self.interceptors?.makeGetSchemaInterceptors() ?? [],
        wrapping: { try await self.getSchema(request: $0, context: $1) }
      )

    case "ListSchemas":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Pubsub_V1_ListSchemasRequest>(),
        responseSerializer: ProtobufSerializer<Google_Pubsub_V1_ListSchemasResponse>(),
        interceptors: self.interceptors?.makeListSchemasInterceptors() ?? [],
        wrapping: { try await self.listSchemas(request: $0, context: $1) }
      )

    case "ListSchemaRevisions":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Pubsub_V1_ListSchemaRevisionsRequest>(),
        responseSerializer: ProtobufSerializer<Google_Pubsub_V1_ListSchemaRevisionsResponse>(),
        interceptors: self.interceptors?.makeListSchemaRevisionsInterceptors() ?? [],
        wrapping: { try await self.listSchemaRevisions(request: $0, context: $1) }
      )

    case "CommitSchema":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Pubsub_V1_CommitSchemaRequest>(),
        responseSerializer: ProtobufSerializer<Google_Pubsub_V1_Schema>(),
        interceptors: self.interceptors?.makeCommitSchemaInterceptors() ?? [],
        wrapping: { try await self.commitSchema(request: $0, context: $1) }
      )

    case "RollbackSchema":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Pubsub_V1_RollbackSchemaRequest>(),
        responseSerializer: ProtobufSerializer<Google_Pubsub_V1_Schema>(),
        interceptors: self.interceptors?.makeRollbackSchemaInterceptors() ?? [],
        wrapping: { try await self.rollbackSchema(request: $0, context: $1) }
      )

    case "DeleteSchemaRevision":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Pubsub_V1_DeleteSchemaRevisionRequest>(),
        responseSerializer: ProtobufSerializer<Google_Pubsub_V1_Schema>(),
        interceptors: self.interceptors?.makeDeleteSchemaRevisionInterceptors() ?? [],
        wrapping: { try await self.deleteSchemaRevision(request: $0, context: $1) }
      )

    case "DeleteSchema":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Pubsub_V1_DeleteSchemaRequest>(),
        responseSerializer: ProtobufSerializer<SwiftProtobuf.Google_Protobuf_Empty>(),
        interceptors: self.interceptors?.makeDeleteSchemaInterceptors() ?? [],
        wrapping: { try await self.deleteSchema(request: $0, context: $1) }
      )

    case "ValidateSchema":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Pubsub_V1_ValidateSchemaRequest>(),
        responseSerializer: ProtobufSerializer<Google_Pubsub_V1_ValidateSchemaResponse>(),
        interceptors: self.interceptors?.makeValidateSchemaInterceptors() ?? [],
        wrapping: { try await self.validateSchema(request: $0, context: $1) }
      )

    case "ValidateMessage":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Pubsub_V1_ValidateMessageRequest>(),
        responseSerializer: ProtobufSerializer<Google_Pubsub_V1_ValidateMessageResponse>(),
        interceptors: self.interceptors?.makeValidateMessageInterceptors() ?? [],
        wrapping: { try await self.validateMessage(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

internal protocol Google_Pubsub_V1_SchemaServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'createSchema'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCreateSchemaInterceptors() -> [ServerInterceptor<Google_Pubsub_V1_CreateSchemaRequest, Google_Pubsub_V1_Schema>]

  /// - Returns: Interceptors to use when handling 'getSchema'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetSchemaInterceptors() -> [ServerInterceptor<Google_Pubsub_V1_GetSchemaRequest, Google_Pubsub_V1_Schema>]

  /// - Returns: Interceptors to use when handling 'listSchemas'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeListSchemasInterceptors() -> [ServerInterceptor<Google_Pubsub_V1_ListSchemasRequest, Google_Pubsub_V1_ListSchemasResponse>]

  /// - Returns: Interceptors to use when handling 'listSchemaRevisions'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeListSchemaRevisionsInterceptors() -> [ServerInterceptor<Google_Pubsub_V1_ListSchemaRevisionsRequest, Google_Pubsub_V1_ListSchemaRevisionsResponse>]

  /// - Returns: Interceptors to use when handling 'commitSchema'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCommitSchemaInterceptors() -> [ServerInterceptor<Google_Pubsub_V1_CommitSchemaRequest, Google_Pubsub_V1_Schema>]

  /// - Returns: Interceptors to use when handling 'rollbackSchema'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeRollbackSchemaInterceptors() -> [ServerInterceptor<Google_Pubsub_V1_RollbackSchemaRequest, Google_Pubsub_V1_Schema>]

  /// - Returns: Interceptors to use when handling 'deleteSchemaRevision'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeDeleteSchemaRevisionInterceptors() -> [ServerInterceptor<Google_Pubsub_V1_DeleteSchemaRevisionRequest, Google_Pubsub_V1_Schema>]

  /// - Returns: Interceptors to use when handling 'deleteSchema'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeDeleteSchemaInterceptors() -> [ServerInterceptor<Google_Pubsub_V1_DeleteSchemaRequest, SwiftProtobuf.Google_Protobuf_Empty>]

  /// - Returns: Interceptors to use when handling 'validateSchema'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeValidateSchemaInterceptors() -> [ServerInterceptor<Google_Pubsub_V1_ValidateSchemaRequest, Google_Pubsub_V1_ValidateSchemaResponse>]

  /// - Returns: Interceptors to use when handling 'validateMessage'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeValidateMessageInterceptors() -> [ServerInterceptor<Google_Pubsub_V1_ValidateMessageRequest, Google_Pubsub_V1_ValidateMessageResponse>]
}

internal enum Google_Pubsub_V1_SchemaServiceServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "SchemaService",
    fullName: "google.pubsub.v1.SchemaService",
    methods: [
      Google_Pubsub_V1_SchemaServiceServerMetadata.Methods.createSchema,
      Google_Pubsub_V1_SchemaServiceServerMetadata.Methods.getSchema,
      Google_Pubsub_V1_SchemaServiceServerMetadata.Methods.listSchemas,
      Google_Pubsub_V1_SchemaServiceServerMetadata.Methods.listSchemaRevisions,
      Google_Pubsub_V1_SchemaServiceServerMetadata.Methods.commitSchema,
      Google_Pubsub_V1_SchemaServiceServerMetadata.Methods.rollbackSchema,
      Google_Pubsub_V1_SchemaServiceServerMetadata.Methods.deleteSchemaRevision,
      Google_Pubsub_V1_SchemaServiceServerMetadata.Methods.deleteSchema,
      Google_Pubsub_V1_SchemaServiceServerMetadata.Methods.validateSchema,
      Google_Pubsub_V1_SchemaServiceServerMetadata.Methods.validateMessage,
    ]
  )

  internal enum Methods {
    internal static let createSchema = GRPCMethodDescriptor(
      name: "CreateSchema",
      path: "/google.pubsub.v1.SchemaService/CreateSchema",
      type: GRPCCallType.unary
    )

    internal static let getSchema = GRPCMethodDescriptor(
      name: "GetSchema",
      path: "/google.pubsub.v1.SchemaService/GetSchema",
      type: GRPCCallType.unary
    )

    internal static let listSchemas = GRPCMethodDescriptor(
      name: "ListSchemas",
      path: "/google.pubsub.v1.SchemaService/ListSchemas",
      type: GRPCCallType.unary
    )

    internal static let listSchemaRevisions = GRPCMethodDescriptor(
      name: "ListSchemaRevisions",
      path: "/google.pubsub.v1.SchemaService/ListSchemaRevisions",
      type: GRPCCallType.unary
    )

    internal static let commitSchema = GRPCMethodDescriptor(
      name: "CommitSchema",
      path: "/google.pubsub.v1.SchemaService/CommitSchema",
      type: GRPCCallType.unary
    )

    internal static let rollbackSchema = GRPCMethodDescriptor(
      name: "RollbackSchema",
      path: "/google.pubsub.v1.SchemaService/RollbackSchema",
      type: GRPCCallType.unary
    )

    internal static let deleteSchemaRevision = GRPCMethodDescriptor(
      name: "DeleteSchemaRevision",
      path: "/google.pubsub.v1.SchemaService/DeleteSchemaRevision",
      type: GRPCCallType.unary
    )

    internal static let deleteSchema = GRPCMethodDescriptor(
      name: "DeleteSchema",
      path: "/google.pubsub.v1.SchemaService/DeleteSchema",
      type: GRPCCallType.unary
    )

    internal static let validateSchema = GRPCMethodDescriptor(
      name: "ValidateSchema",
      path: "/google.pubsub.v1.SchemaService/ValidateSchema",
      type: GRPCCallType.unary
    )

    internal static let validateMessage = GRPCMethodDescriptor(
      name: "ValidateMessage",
      path: "/google.pubsub.v1.SchemaService/ValidateMessage",
      type: GRPCCallType.unary
    )
  }
}
